baseURL = "https://httpcodes.fyi/"
languageCode = "en-us"
title = "HTTP Status Codes"

enableGitInfo = true

[permalinks]
  codes = "/:filename/"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = [
    "HTML",
    "RSS",
    "HEADERS",
    "REDIRECTS"
  ]

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats]
  [outputFormats.REDIRECTS]
    mediatype = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true
  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true
