[build]
publish = "public"
command = "hugo --gc"

[build.environment]
HUGO_VERSION = "0.63.1"
HUGO_ENABLEGITINFO = "true"
# Required for PostCSS work
NODE_ENV = "production"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"
